version: '3.4'

services:
  elasticexample:  
    image: ${DOCKER_REGISTRY-}elasticexample
    build:
      context: .
      dockerfile: ElasticExample/Dockerfile
    depends_on:
     - elasticsearchengine
    links:
     - elasticsearchengine
    #networks:
    #  - composenet2
  elasticsearchengine:
     image: elastic/elasticsearch:7.17.6
     environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
     ports:
             - 9200:9200
             - 9300:9300
     #networks:
     # - composenet2
  kibana:
    image: kibana:7.17.6
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearchengine:9200
    depends_on:
      - elasticsearchengine
    ports:
      - 5601:5601
    #networks:
    #  - composenet2
#networks:
#  composenet2:

    
  
