version: '3.4'

services:
  elasticexample:
    image: elasticexample:dev
    container_name: ElasticExample
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ElasticExample"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\Mohammadali.Ebrahimz\Desktop\Elastic\ElasticSearch\ElasticExample:/app
      - C:\Users\Mohammadali.Ebrahimz\Desktop\Elastic\ElasticSearch:/src
      - C:\Users\Mohammadali.Ebrahimz\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\Mohammadali.Ebrahimz\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/ElasticExample.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true